modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nova-Committee/ScreenshotSharing/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://github.com/Nova-Committee/ScreenshotSharing"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies."${mod_id}"]]
modId = "chatimage"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
